sonar.organization=ts-solaris
sonar.projectKey=TS-Solaris_library

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src/main/kotlin
