services:
  postgres:
    image: postgres:latest
    container_name: postgres-library
    restart: always
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    ports:
      - "5432:5432"
